-- MedSlime achievement MVP
-- Run in Supabase SQL Editor. Safe to run again.

create table if not exists public.achievement_claims (
    id bigint generated by default as identity primary key,
    user_key text not null,
    achievement_id text not null,
    unlocked_at timestamptz not null default now(),
    claimed_at timestamptz,
    reward_type text not null check (reward_type in ('coins', 'tickets')),
    reward_amount integer not null check (reward_amount >= 0),
    created_at timestamptz not null default now(),
    unique (user_key, achievement_id)
);

create index if not exists achievement_claims_user_key_idx
    on public.achievement_claims (user_key);

create index if not exists achievement_claims_achievement_id_idx
    on public.achievement_claims (achievement_id);

-- Prototype stage: the app is not using Supabase Auth yet, so the app writes with
-- the anon key. Explicitly grant CRUD privileges and keep RLS disabled for this table.
alter table public.achievement_claims disable row level security;
grant usage on schema public to anon, authenticated;
grant select, insert, update on table public.achievement_claims to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

comment on table public.achievement_claims is
'MedSlime prototype achievement unlock/claim records. user_key will be replaced by the authenticated user id after login is implemented.';
