-- MedSlime achievement MVP
-- Run once in Supabase SQL Editor.

create table if not exists public.achievement_claims (
    id bigint generated by default as identity primary key,
    user_key text not null,
    achievement_id text not null,
    unlocked_at timestamptz not null default now(),
    claimed_at timestamptz,
    reward_type text not null check (reward_type in ('coins', 'tickets')),
    reward_amount integer not null check (reward_amount >= 0),
    created_at timestamptz not null default now(),
    unique (user_key, achievement_id)
);

create index if not exists achievement_claims_user_key_idx
    on public.achievement_claims (user_key);

create index if not exists achievement_claims_achievement_id_idx
    on public.achievement_claims (achievement_id);

comment on table public.achievement_claims is
'MedSlime prototype achievement unlock/claim records. user_key will be replaced by the authenticated user id after login is implemented.';
