-- MedSlime focus-session history MVP
-- Run once in Supabase SQL Editor. Safe to run again.

create table if not exists public.focus_sessions (
    id bigint generated by default as identity primary key,
    user_key text not null,
    session_token text not null,
    started_at timestamptz not null,
    ended_at timestamptz not null,
    planned_minutes integer not null default 0 check (planned_minutes >= 0),
    focused_seconds integer not null default 0 check (focused_seconds >= 0),
    earned_coins integer not null default 0 check (earned_coins >= 0),
    completed boolean not null default false,
    slime_name text,
    created_at timestamptz not null default now(),
    unique (user_key, session_token)
);

create index if not exists focus_sessions_user_started_idx
    on public.focus_sessions (user_key, started_at desc);

alter table public.focus_sessions disable row level security;
grant select, insert, update on table public.focus_sessions to anon, authenticated;
grant usage, select on sequence public.focus_sessions_id_seq to anon, authenticated;

comment on table public.focus_sessions is
'MedSlime MVP per-focus-round history. user_key is temporary until authentication exists.';
