from pathlib import Path

path = Path('streamlit_app.py')
text = path.read_text(encoding='utf-8')

old = '''def _render_strikeable_options(prefix, index, options, answer_store, struck_store):\n    struck = set(struck_store.get(index, []))\n    selected_index = answer_store.get(index)\n    for option_index, option in enumerate(options):\n        circle_col, text_col = st.columns([0.075, 0.925], gap="small")\n        with circle_col:\n            circle = "●" if selected_index == option_index else "○"\n            if st.button(circle, key=f"{prefix}_pick_{index}_{option_index}", help="選擇這個答案"):\n                answer_store[index] = option_index\n                st.rerun()\n        with text_col:\n            is_struck = option_index in struck\n            key_state = "on" if is_struck else "off"\n            label = normalize_scientific_notation(option)\n            if st.button(label, key=f"{prefix}_strike_{key_state}_{index}_{option_index}", use_container_width=True, help="劃掉 / 取消劃掉這個選項"):\n                if is_struck:\n                    struck.discard(option_index)\n                else:\n                    struck.add(option_index)\n                struck_store[index] = sorted(struck)\n                st.rerun()\n'''
new = '''def _render_strikeable_options(prefix, index, options, answer_store, struck_store):\n    struck = set(struck_store.get(index, []))\n    selected_index = answer_store.get(index)\n    for option_index, option in enumerate(options):\n        circle_col, text_col = st.columns([0.09, 0.91], gap="small")\n        with circle_col:\n            circle = "●" if selected_index == option_index else "○"\n            with st.container(key=f"{prefix}_pick_wrap_{index}_{option_index}"):\n                if st.button(circle, key=f"{prefix}_pick_{index}_{option_index}"):\n                    answer_store[index] = option_index\n                    st.rerun()\n        with text_col:\n            is_struck = option_index in struck\n            key_state = "on" if is_struck else "off"\n            label = normalize_scientific_notation(option)\n            with st.container(key=f"{prefix}_strike_{key_state}_{index}_{option_index}"):\n                if st.button(label, key=f"{prefix}_strike_btn_{index}_{option_index}", use_container_width=True):\n                    if is_struck:\n                        struck.discard(option_index)\n                    else:\n                        struck.add(option_index)\n                    struck_store[index] = sorted(struck)\n                    st.rerun()\n'''
if old not in text:
    raise RuntimeError('strikeable options helper not found')
text = text.replace(old, new, 1)

old_css = '''    [class*="st-key-national_strike_on_"] button p,\n    [class*="st-key-material_strike_on_"] button p { text-decoration:line-through !important; opacity:.42 !important; }\n    [class*="st-key-national_strike_"] button,\n    [class*="st-key-material_strike_"] button { justify-content:flex-start !important; text-align:left !important; background:rgba(255,255,255,.82) !important; color:#244c39 !important; border:1px solid #e0ebe5 !important; box-shadow:none !important; }\n    [class*="st-key-national_pick_"] button,\n    [class*="st-key-material_pick_"] button { min-width:38px !important; width:38px !important; padding:0 !important; border:none !important; background:transparent !important; box-shadow:none !important; font-size:1.15rem !important; }\n'''
new_css = '''    [class*="st-key-national_strike_on_"] button p,\n    [class*="st-key-material_strike_on_"] button p { text-decoration:line-through !important; opacity:.42 !important; }\n    [class*="st-key-national_strike_"] button,\n    [class*="st-key-material_strike_"] button { justify-content:flex-start !important; text-align:left !important; background:rgba(255,255,255,.82) !important; color:#244c39 !important; border:1px solid #e0ebe5 !important; box-shadow:none !important; padding-left:.9rem !important; }\n    [class*="st-key-national_strike_"] button p,\n    [class*="st-key-material_strike_"] button p { width:100% !important; text-align:left !important; }\n    [class*="st-key-national_pick_wrap_"] button,\n    [class*="st-key-material_pick_wrap_"] button { display:flex !important; align-items:center !important; justify-content:center !important; min-width:38px !important; width:38px !important; min-height:38px !important; height:38px !important; padding:0 !important; margin:0 auto !important; border:none !important; background:transparent !important; color:#17212a !important; box-shadow:none !important; font-size:1.2rem !important; }\n    [class*="st-key-national_pick_wrap_"] button p,\n    [class*="st-key-material_pick_wrap_"] button p { color:#17212a !important; opacity:1 !important; font-size:1.2rem !important; line-height:1 !important; }\n'''
if old_css not in text:
    raise RuntimeError('strike CSS anchor not found')
text = text.replace(old_css, new_css, 1)

path.write_text(text, encoding='utf-8')
print('fixed strike option alignment, radio circles, and hover tooltips')
