from pathlib import Path

path = Path('streamlit_app.py')
text = path.read_text(encoding='utf-8')

css_anchor = '    .companion-panel { display:flex; gap:1.7rem; align-items:center; background:linear-gradient(135deg,#eefaf3,#ffffff 62%,#edf8fc); border:1px solid #d7eadf; border-radius:30px; padding:1.55rem 1.7rem; box-shadow:0 16px 38px rgba(30,82,51,.065); margin:.5rem 0 1.25rem; overflow:hidden; }\n'
css_add = css_anchor + '''    [class*="st-key-companion_panel_live"] { background:linear-gradient(135deg,#eefaf3,#ffffff 62%,#edf8fc); border:1px solid #d7eadf; border-radius:30px; padding:1.55rem 1.7rem; box-shadow:0 16px 38px rgba(30,82,51,.065); margin:.5rem 0 1.25rem; overflow:hidden; }\n    [class*="st-key-companion_panel_live"] .companion-art { width:100%; min-width:0; }\n    [class*="st-key-companion_panel_live"] [data-testid="stHorizontalBlock"] { align-items:center; }\n'''
if '[class*="st-key-companion_panel_live"] {' not in text:
    if css_anchor not in text:
        raise RuntimeError('companion css anchor not found')
    text = text.replace(css_anchor, css_add, 1)

old = '''    rarity_class = f"rarity-{current['rarity']}"\n    st.markdown(\n        '<div class="companion-panel">'\n        f'<div class="companion-art">{slime_avatar_markup(current, size="hero", selected=True)}</div>'\n        '<div class="companion-info">'\n        f'<div class="companion-topline"><span class="rarity-chip {rarity_class}">{current["rarity"]}</span>'\n        f'<span class="owned-chip">✓ 陪伴中</span></div>'\n        f'<div class="companion-species">{current["name"]} · {current["tagline"]}</div>'\n        f'<div class="companion-level-row"><span>Lv.{progress["level"]}</span><span>{progress["exp"]} / 100 EXP</span></div>'\n        f'<div class="companion-xp"><span style="width:{min(100, int(progress["exp"]))}%"></span></div>'\n        f'<div class="companion-meta"><span>🧩 專屬碎片 {progress.get("fragments", 0)}</span><span>🎨 三階段成長：規劃中</span><span>🎩 裝扮：下一階段</span></div>'\n        '<div class="art-placeholder-note">目前角色為介面占位造型；正式美術會在角色設計定稿後替換。</div>'\n        '</div></div>',\n        unsafe_allow_html=True,\n    )\n\n    # The nickname itself is the edit control; keep the editor hidden until requested.\n    if st.button(f"{nickname} ✏️", key=f"slime_name_button_{current['theme']}"):\n        st.session_state.slime_name_editing = not st.session_state.slime_name_editing\n        st.rerun()\n    if st.session_state.slime_name_editing:\n        with st.container(key=f"slime_nickname_editor_{current['theme']}"):\n            new_nickname = st.text_input("史萊姆暱稱", value=nickname, max_chars=16, key=f"nickname_{current['name']}")\n            save_col, cancel_col = st.columns(2)\n            with save_col:\n                if st.button("儲存名字", type="primary", use_container_width=True, key=f"save_nickname_{current['theme']}"):\n                    st.session_state.slime_nicknames[current["name"]] = new_nickname.strip() or current["name"].replace("史萊姆", "")\n                    st.session_state.slime_name_editing = False\n                    st.rerun()\n            with cancel_col:\n                if st.button("取消", use_container_width=True, key=f"cancel_nickname_{current['theme']}"):\n                    st.session_state.slime_name_editing = False\n                    st.rerun()\n\n'''
new = '''    rarity_class = f"rarity-{current['rarity']}"\n    with st.container(key="companion_panel_live"):\n        art_col, info_col = st.columns([1, 3], gap="large", vertical_alignment="center")\n        with art_col:\n            st.markdown(\n                f'<div class="companion-art">{slime_avatar_markup(current, size="hero", selected=True)}</div>',\n                unsafe_allow_html=True,\n            )\n        with info_col:\n            st.markdown(\n                f'<div class="companion-topline"><span class="rarity-chip {rarity_class}">{current["rarity"]}</span>'\n                f'<span class="owned-chip">✓ 陪伴中</span></div>',\n                unsafe_allow_html=True,\n            )\n            # The nickname itself is the edit control, exactly where the name is displayed.\n            if st.button(f"{nickname} ✏️", key=f"slime_name_button_{current['theme']}"):\n                st.session_state.slime_name_editing = not st.session_state.slime_name_editing\n                st.rerun()\n            if st.session_state.slime_name_editing:\n                with st.container(key=f"slime_nickname_editor_{current['theme']}"):\n                    new_nickname = st.text_input("史萊姆暱稱", value=nickname, max_chars=16, key=f"nickname_{current['name']}")\n                    save_col, cancel_col = st.columns(2)\n                    with save_col:\n                        if st.button("儲存名字", type="primary", use_container_width=True, key=f"save_nickname_{current['theme']}"):\n                            st.session_state.slime_nicknames[current["name"]] = new_nickname.strip() or current["name"].replace("史萊姆", "")\n                            st.session_state.slime_name_editing = False\n                            st.rerun()\n                    with cancel_col:\n                        if st.button("取消", use_container_width=True, key=f"cancel_nickname_{current['theme']}"):\n                            st.session_state.slime_name_editing = False\n                            st.rerun()\n            st.markdown(\n                f'<div class="companion-species">{current["name"]} · {current["tagline"]}</div>'\n                f'<div class="companion-level-row"><span>Lv.{progress["level"]}</span><span>{progress["exp"]} / 100 EXP</span></div>'\n                f'<div class="companion-xp"><span style="width:{min(100, int(progress["exp"]))}%"></span></div>'\n                f'<div class="companion-meta"><span>🧩 專屬碎片 {progress.get("fragments", 0)}</span><span>🎨 三階段成長：規劃中</span><span>🎩 裝扮：下一階段</span></div>'\n                '<div class="art-placeholder-note">目前角色為介面占位造型；正式美術會在角色設計定稿後替換。</div>',\n                unsafe_allow_html=True,\n            )\n\n'''
if old not in text:
    raise RuntimeError('companion live block anchor not found')
text = text.replace(old, new, 1)

path.write_text(text, encoding='utf-8')
print('placed slime nickname edit control inline in companion panel')
