from pathlib import Path

p = Path('streamlit_app.py')
s = p.read_text(encoding='utf-8')

# 1) Make desktop collection cards fit their columns and add compact companion info.
old_css = '.slime-v2-card{border:1px solid #dbe9e1;background:rgba(255,255,255,.9);border-radius:20px;padding:.7rem;text-align:center;min-height:210px;box-shadow:0 8px 22px rgba(32,85,54,.05)}.slime-v2-card.locked{background:#f5f8f6}.slime-v2-card-name{font-weight:900;color:#1c4130;font-size:.88rem;min-height:2.3rem;margin-top:.25rem}.slime-v2-meta{font-size:.72rem;color:#789083;margin-top:.18rem}'
new_css = '.slime-v2-card{border:1px solid #dbe9e1;background:rgba(255,255,255,.9);border-radius:20px;padding:.72rem;text-align:center;min-height:205px;box-shadow:0 8px 22px rgba(32,85,54,.05);overflow:hidden}.slime-v2-card.locked{background:#f5f8f6}.slime-v2-card .official-slime-art-card{width:100%;max-width:128px;height:104px;margin:0 auto}.slime-v2-card .catalog-slime-card{width:100%;max-width:128px;height:104px;margin:0 auto}.slime-v2-card-name{font-weight:900;color:#1c4130;font-size:.88rem;min-height:2.3rem;margin-top:.25rem}.slime-v2-meta{font-size:.72rem;color:#789083;margin-top:.18rem}.slime-v2-card-companion{display:inline-flex;align-items:center;justify-content:center;margin-top:.35rem;padding:.24rem .55rem;border-radius:999px;background:#e9f8ef;border:1px solid #cfe9da;color:#28754b;font-size:.7rem;font-weight:900}.slime-v2-card-frag{margin-top:.35rem;color:#557768;font-size:.7rem;font-weight:800;line-height:1.35}'
assert old_css in s
s = s.replace(old_css, new_css, 1)

# 2) Use 4 columns on desktop instead of 5 so artwork/cards do not overflow.
s = s.replace('for start in range(0,len(visible),5):\n            cols=st.columns(5)\n            for i,col in enumerate(cols):', 'for start in range(0,len(visible),4):\n            cols=st.columns(4)\n            for i,col in enumerate(cols):', 1)

# 3) Put companion + exclusive accessory fragment status directly inside the companion slime card.
old_card = '''                with col:\n                    avatar = slime_avatar_markup(x, size="card", locked=not owned, mystery=(x["rarity"]=="SSR" and not owned))\n                    st.markdown(f'<div class="slime-v2-card{"" if owned else " locked"}">{avatar}<div class="slime-v2-card-name">{html.escape(title)}</div><div class="slime-v2-meta">{x["rarity"]} · {"已擁有" if owned else "尚未取得"}</div></div>', unsafe_allow_html=True)\n                    if owned: st.progress(min(1.0,frag/30),text=f"碎片 {frag} / 30")\n                    if st.button("查看詳情",key=f"slime_v2_{x['theme']}",use_container_width=True):\n                        st.session_state.slime_detail_name=x["name"]; st.rerun()\n'''
new_card = '''                with col:\n                    avatar = slime_avatar_markup(x, size="card", locked=not owned, mystery=(x["rarity"]=="SSR" and not owned))\n                    is_companion = owned and x["name"] == st.session_state.selected_slime\n                    companion_line = '<div class="slime-v2-card-companion">✓ 陪伴中</div>' if is_companion else ''\n                    if is_companion:\n                        acc_unlocked = st.session_state.slime_accessories.get(x["name"], False)\n                        if acc_unlocked:\n                            fragment_line = f'<div class="slime-v2-card-frag">✨ 專屬飾品已解鎖</div>'\n                        else:\n                            remain = max(0, 30 - frag)\n                            fragment_line = f'<div class="slime-v2-card-frag">專屬飾品還差 {remain} 碎片</div>'\n                    else:\n                        fragment_line = ''\n                    st.markdown(f'<div class="slime-v2-card{"" if owned else " locked"}">{avatar}<div class="slime-v2-card-name">{html.escape(title)}</div><div class="slime-v2-meta">{x["rarity"]} · {"已擁有" if owned else "尚未取得"}</div>{companion_line}{fragment_line}</div>', unsafe_allow_html=True)\n                    if owned and not is_companion: st.progress(min(1.0,frag/30),text=f"碎片 {frag} / 30")\n                    if st.button("查看詳情",key=f"slime_v2_{x['theme']}",use_container_width=True):\n                        st.session_state.slime_detail_name=x["name"]; st.rerun()\n'''
assert old_card in s
s = s.replace(old_card, new_card, 1)

# 4) Do not render a second detail card when the currently viewed slime is already the active companion.
old_detail_start = '''    with right:\n        x=SLIME_BY_NAME.get(st.session_state.slime_detail_name,SLIME_CATALOG[0]); owned=x["name"] in st.session_state.collection\n        title="???" if x["rarity"]=="SSR" and not owned else x["name"]\n        detail_avatar = slime_avatar_markup(x, size="home", locked=not owned, mystery=(x["rarity"]=="SSR" and not owned))\n        companion_badge = '<div style="text-align:center"><span class="slime-v2-companion-badge">✓ 陪伴中</span></div>' if owned and x["name"]==st.session_state.selected_slime else ''\n        st.markdown(f'<div class="slime-v2-detail">{detail_avatar}<div class="slime-v2-detail-name">{html.escape(title)}</div><div class="slime-v2-rarity">{x["rarity"]}</div>{companion_badge}</div>', unsafe_allow_html=True)\n        st.write(x["tagline"] if owned or x["rarity"]!="SSR" else "取得後才會揭曉真正身分。")\n        if owned:\n'''
new_detail_start = '''    with right:\n        x=SLIME_BY_NAME.get(st.session_state.slime_detail_name,SLIME_CATALOG[0]); owned=x["name"] in st.session_state.collection\n        title="???" if x["rarity"]=="SSR" and not owned else x["name"]\n        if owned and x["name"] == st.session_state.selected_slime:\n            st.markdown('<div class="slime-v2-detail" style="text-align:center"><div class="slime-v2-detail-name">目前陪伴史萊姆</div><div class="slime-v2-meta">資訊已整合在左側角色卡片中</div></div>', unsafe_allow_html=True)\n        else:\n            detail_avatar = slime_avatar_markup(x, size="home", locked=not owned, mystery=(x["rarity"]=="SSR" and not owned))\n            st.markdown(f'<div class="slime-v2-detail">{detail_avatar}<div class="slime-v2-detail-name">{html.escape(title)}</div><div class="slime-v2-rarity">{x["rarity"]}</div></div>', unsafe_allow_html=True)\n            st.write(x["tagline"] if owned or x["rarity"]!="SSR" else "取得後才會揭曉真正身分。")\n        if owned and x["name"] != st.session_state.selected_slime:\n'''
assert old_detail_start in s
s = s.replace(old_detail_start, new_detail_start, 1)

# 5) Remove the collection progress summary card and its progress bar entirely.
start = s.index('    owned=len([x for x in SLIME_CATALOG if x["name"] in st.session_state.collection])\n', s.index('def slime_page():'))
end = s.index('\n\ndef achievements_page():', start)
s = s[:start] + s[end:]

p.write_text(s, encoding='utf-8')
